version: "3"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=user
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    volumes:
      - ./src:/app/src
    command: bash -c "./manage.py migrate && ./manage.py init_group && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env