# Generated by Django 3.1.4 on 2021-09-20 11:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('closed', 'closed'), ('suspended', 'suspended'), ('archived', 'archived')], default='active', max_length=20)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='restaurant_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'restaurant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('menu_date', models.DateField()),
                ('price', models.FloatField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_restaurant', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu',
                'db_table': 'menu',
                'ordering': ['-menu_date'],
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='restaurant_name_d51441_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status'], name='restaurant_status_f5fbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['name'], name='menu_name_9b231d_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_date'], name='menu_menu_da_729151_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('menu_date', 'restaurant')},
        ),
    ]
