"""
Django settings for user_app project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from user_app.settings.app_vars import *
from user_app.settings.apps import *
from user_app.settings.base import *
from user_app.settings.database import *
from user_app.settings.logger import *
from user_app.settings.third_party import *

__all__ = ['celery_app']
