# Generated by Django 3.2 on 2022-01-25 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('device_name', models.CharField(blank=True, max_length=50)),
                ('device_model', models.CharField(blank=True, max_length=50)),
                ('device_make', models.CharField(blank=True, max_length=50)),
                ('device_token', models.CharField(blank=True, max_length=250, unique=True)),
                ('fcm_token', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('is_fingerprint_enabled', models.BooleanField(blank=True, default=False)),
                ('is_passcode_enabled', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'device',
                'ordering': ['-id'],
            },
        ),
    ]
