# Generated by Django 3.1.4 on 2021-09-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('voting_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='votes_employee', to='users.employee')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='votes_manu', to='restaurant.menu')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'vote',
                'ordering': ['-voting_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('publish_date', models.DateField(unique=True)),
                ('number_of_votes', models.IntegerField()),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='result', to='restaurant.menu')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'result',
                'db_table': 'result',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voting_date'], name='vote_voting__918b3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voting_date', 'employee')},
        ),
    ]
